# Generated by Django 5.0.3 on 2024-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='davomiylik',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='narx',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
