# Generated by Django 5.0.3 on 2024-04-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_tarif_davomiylik_tarif_narx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinoAktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.aktyor')),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.kino')),
            ],
        ),
    ]
