# Generated by Django 5.0.3 on 2024-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='matn',
            field=models.CharField(max_length=300),
        ),
    ]
